// <auto-generated />
using System;
using DooKamp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DooKamp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DooKampDbContext))]
    [Migration("20261006202129_AddVocabularyCode")]
    partial class AddVocabularyCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("DooKamp.Domain.Entities.Audio.LessonContentAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonContentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LessonContentId", "LanguageId")
                        .IsUnique();

                    b.ToTable("LessonContentAudios");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Audio.VocabularyAudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("VocabularyId", "LanguageId")
                        .IsUnique();

                    b.ToTable("VocabularyAudios");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentTopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentTopicId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Languages.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "Order")
                        .IsUnique();

                    b.ToTable("LessonContents");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonContentLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonContentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LessonContentId", "LanguageId")
                        .IsUnique();

                    b.ToTable("LessonContentLanguages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonLocationGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("LessonId", "LocationId", "GradeId")
                        .IsUnique();

                    b.ToTable("LessonLocationGrades");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonTopic", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("LessonId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("LessonTopics");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Media.LessonContentMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("LessonContentId", "MediaId")
                        .IsUnique();

                    b.ToTable("LessonContentMedias");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Media.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Media.VocabularyMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("VocabularyId", "MediaId")
                        .IsUnique();

                    b.ToTable("VocabularyMedias");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuizQuestionId", "Order")
                        .IsUnique();

                    b.ToTable("QuizOptions");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizOptionLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuizOptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("QuizOptionId", "LanguageId")
                        .IsUnique();

                    b.ToTable("QuizOptionLanguages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LessonContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonContentId");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("LessonId", "Order")
                        .IsUnique();

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizQuestionLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("QuizQuestionId", "LanguageId")
                        .IsUnique();

                    b.ToTable("QuizQuestionLanguages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Vocabs.LessonContentVocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonContentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.HasIndex("LessonContentId", "VocabularyId")
                        .IsUnique();

                    b.ToTable("LessonContentVocabularies");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Vocabs.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Vocabs.VocabularyLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("VocabularyId", "LanguageId")
                        .IsUnique();

                    b.ToTable("VocabularyLanguages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Audio.LessonContentAudio", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Languages.Language", "Language")
                        .WithMany("LessonContentAudios")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Lessons.LessonContent", "LessonContent")
                        .WithMany("Audios")
                        .HasForeignKey("LessonContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LessonContent");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Audio.VocabularyAudio", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Languages.Language", "Language")
                        .WithMany("VocabularyAudios")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Vocabs.Vocabulary", "Vocabulary")
                        .WithMany("Audios")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Topic", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Curriculum.Topic", "ParentTopic")
                        .WithMany("ChildTopics")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DooKamp.Domain.Entities.Curriculum.Subject", "Subject")
                        .WithMany("Topics")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTopic");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonContent", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Lessons.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonContentLanguage", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Languages.Language", "Language")
                        .WithMany("LessonContentLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Lessons.LessonContent", "LessonContent")
                        .WithMany("Languages")
                        .HasForeignKey("LessonContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LessonContent");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonLocationGrade", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Curriculum.Grade", "Grade")
                        .WithMany("LessonLocationGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Lessons.Lesson", "Lesson")
                        .WithMany("LessonLocationGrades")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Curriculum.Location", "Location")
                        .WithMany("LessonLocationGrades")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Lesson");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonTopic", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Lessons.Lesson", "Lesson")
                        .WithMany("LessonTopics")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Curriculum.Topic", "Topic")
                        .WithMany("LessonTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Media.LessonContentMedia", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Lessons.LessonContent", "LessonContent")
                        .WithMany("MediaItems")
                        .HasForeignKey("LessonContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Media.Media", "Media")
                        .WithMany("LessonContentMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonContent");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Media.VocabularyMedia", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Media.Media", "Media")
                        .WithMany("VocabularyMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Vocabs.Vocabulary", "Vocabulary")
                        .WithMany("VocabularyMedias")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizOption", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Quizzes.QuizQuestion", "QuizQuestion")
                        .WithMany("Options")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizOptionLanguage", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Languages.Language", "Language")
                        .WithMany("QuizOptionLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Quizzes.QuizOption", "QuizOption")
                        .WithMany("Languages")
                        .HasForeignKey("QuizOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("QuizOption");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizQuestion", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Lessons.LessonContent", "LessonContent")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("LessonContentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DooKamp.Domain.Entities.Lessons.Lesson", "Lesson")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Quizzes.QuestionType", "QuestionType")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("LessonContent");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizQuestionLanguage", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Languages.Language", "Language")
                        .WithMany("QuizQuestionLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Quizzes.QuizQuestion", "QuizQuestion")
                        .WithMany("Languages")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Vocabs.LessonContentVocabulary", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Lessons.LessonContent", "LessonContent")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Vocabs.Vocabulary", "Vocabulary")
                        .WithMany("LessonContentVocabularies")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonContent");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Vocabs.VocabularyLanguage", b =>
                {
                    b.HasOne("DooKamp.Domain.Entities.Languages.Language", "Language")
                        .WithMany("VocabularyLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DooKamp.Domain.Entities.Vocabs.Vocabulary", "Vocabulary")
                        .WithMany("Languages")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Grade", b =>
                {
                    b.Navigation("LessonLocationGrades");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Location", b =>
                {
                    b.Navigation("LessonLocationGrades");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Subject", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Curriculum.Topic", b =>
                {
                    b.Navigation("ChildTopics");

                    b.Navigation("LessonTopics");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Languages.Language", b =>
                {
                    b.Navigation("LessonContentAudios");

                    b.Navigation("LessonContentLanguages");

                    b.Navigation("QuizOptionLanguages");

                    b.Navigation("QuizQuestionLanguages");

                    b.Navigation("VocabularyAudios");

                    b.Navigation("VocabularyLanguages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.Lesson", b =>
                {
                    b.Navigation("LessonContents");

                    b.Navigation("LessonLocationGrades");

                    b.Navigation("LessonTopics");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Lessons.LessonContent", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Languages");

                    b.Navigation("MediaItems");

                    b.Navigation("QuizQuestions");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Media.Media", b =>
                {
                    b.Navigation("LessonContentMedias");

                    b.Navigation("VocabularyMedias");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuestionType", b =>
                {
                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizOption", b =>
                {
                    b.Navigation("Languages");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Quizzes.QuizQuestion", b =>
                {
                    b.Navigation("Languages");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("DooKamp.Domain.Entities.Vocabs.Vocabulary", b =>
                {
                    b.Navigation("Audios");

                    b.Navigation("Languages");

                    b.Navigation("LessonContentVocabularies");

                    b.Navigation("VocabularyMedias");
                });
#pragma warning restore 612, 618
        }
    }
}
