namespace Dookamp.Infrastructure.Seed;

public static class LessonContentLanguageSeedData
{
    public static IReadOnlyList<LessonContentLanguageSeed> AdditionalLanguages { get; } =
    [
        new() { Id = 33, LessonContentId = 1, LanguageId = 2, Text = "날씨는 우리가 밖에 나갔을 때 느끼는 것입니다." },
        new() { Id = 34, LessonContentId = 1, LanguageId = 3, Text = "El tiempo es lo que sentimos cuando salimos." },
        new() { Id = 35, LessonContentId = 1, LanguageId = 4, Text = "天气是我们外出时感受到的情况。" },
        new() { Id = 36, LessonContentId = 2, LanguageId = 2, Text = "날씨에는 온도, 강수량, 바람, 습도, 구름의 양, 대기압, 일조량 등이 포함됩니다." },
        new() { Id = 37, LessonContentId = 2, LanguageId = 3, Text = "Incluye la temperatura, la precipitación, el viento, la humedad, la nubosidad, la presión atmosférica y la luz solar." },
        new() { Id = 38, LessonContentId = 2, LanguageId = 4, Text = "天气包括温度、降水、风、湿度、云量、大气压和日照等。" },
        new() { Id = 39, LessonContentId = 3, LanguageId = 2, Text = "온도는 얼마나 덥거나 추운지를 나타냅니다." },
        new() { Id = 40, LessonContentId = 3, LanguageId = 3, Text = "La temperatura indica qué tan caliente o frío está." },
        new() { Id = 41, LessonContentId = 3, LanguageId = 4, Text = "温度表示天气有多热或多冷。" },
        new() { Id = 42, LessonContentId = 4, LanguageId = 2, Text = "온도를 측정할 때는 온도계를 사용합니다." },
        new() { Id = 43, LessonContentId = 4, LanguageId = 3, Text = "Usamos termómetros para medirla." },
        new() { Id = 44, LessonContentId = 4, LanguageId = 4, Text = "我们用温度计来测量温度。" },
        new() { Id = 45, LessonContentId = 5, LanguageId = 2, Text = "강수는 하늘에서 떨어지는 물입니다." },
        new() { Id = 46, LessonContentId = 5, LanguageId = 3, Text = "La precipitación es el agua que cae del cielo." },
        new() { Id = 47, LessonContentId = 5, LanguageId = 4, Text = "降水是从天空中落下的水。" },
        new() { Id = 48, LessonContentId = 6, LanguageId = 2, Text = "여기에는 비, 눈, 진눈깨비, 우박이 포함됩니다." },
        new() { Id = 49, LessonContentId = 6, LanguageId = 3, Text = "Incluye lluvia, nieve, aguanieve y granizo." },
        new() { Id = 50, LessonContentId = 6, LanguageId = 4, Text = "降水包括雨、雪、雨夹雪和冰雹。" },
        new() { Id = 51, LessonContentId = 7, LanguageId = 2, Text = "바람은 움직이는 공기입니다." },
        new() { Id = 52, LessonContentId = 7, LanguageId = 3, Text = "El viento es aire en movimiento." },
        new() { Id = 53, LessonContentId = 7, LanguageId = 4, Text = "风是流动的空气。" },
        new() { Id = 54, LessonContentId = 8, LanguageId = 2, Text = "풍속은 풍속계라는 도구로 측정합니다." },
        new() { Id = 55, LessonContentId = 8, LanguageId = 3, Text = "Medimos la velocidad del viento con un instrumento llamado anemómetro." },
        new() { Id = 56, LessonContentId = 8, LanguageId = 4, Text = "我们用一种叫风速计的仪器来测量风速。" },
        new() { Id = 57, LessonContentId = 9, LanguageId = 2, Text = "습도는 공기 중에 물이 얼마나 많이 들어 있는지를 나타냅니다." },
        new() { Id = 58, LessonContentId = 9, LanguageId = 3, Text = "La humedad indica cuánta agua hay en el aire." },
        new() { Id = 59, LessonContentId = 9, LanguageId = 4, Text = "湿度表示空气中含有多少水分。" },
        new() { Id = 60, LessonContentId = 10, LanguageId = 2, Text = "습도는 습도계로 측정합니다." },
        new() { Id = 61, LessonContentId = 10, LanguageId = 3, Text = "Usamos un higrómetro para medirla." },
        new() { Id = 62, LessonContentId = 10, LanguageId = 4, Text = "我们用湿度计来测量湿度。" },
        new() { Id = 63, LessonContentId = 11, LanguageId = 2, Text = "운량은 하늘에 구름이 얼마나 많이 있는지를 나타냅니다." },
        new() { Id = 64, LessonContentId = 11, LanguageId = 3, Text = "La nubosidad indica cuántas nubes hay en el cielo." },
        new() { Id = 65, LessonContentId = 11, LanguageId = 4, Text = "云量表示天空中有多少云。" },
        new() { Id = 66, LessonContentId = 12, LanguageId = 2, Text = "대기압은 공기가 누르는 힘입니다." },
        new() { Id = 67, LessonContentId = 12, LanguageId = 3, Text = "La presión atmosférica es la fuerza que ejerce el aire." },
        new() { Id = 68, LessonContentId = 12, LanguageId = 4, Text = "大气压是空气产生的压力。" },
        new() { Id = 69, LessonContentId = 13, LanguageId = 2, Text = "저기압은 나쁜 날씨를 가져올 수 있고, 고기압은 좋은 날씨를 가져올 수 있습니다." },
        new() { Id = 70, LessonContentId = 13, LanguageId = 3, Text = "La baja presión puede traer mal tiempo, y la alta presión puede traer buen tiempo." },
        new() { Id = 71, LessonContentId = 13, LanguageId = 4, Text = "低气压可能带来坏天气，高气压可能带来好天气。" },
        new() { Id = 72, LessonContentId = 14, LanguageId = 2, Text = "일조량은 우리에게 도달하는 햇빛의 양입니다." },
        new() { Id = 73, LessonContentId = 14, LanguageId = 3, Text = "La luz solar es la cantidad de luz del sol que llega hasta nosotros." },
        new() { Id = 74, LessonContentId = 14, LanguageId = 4, Text = "日照是到达我们这里的阳光量。" },
        new() { Id = 75, LessonContentId = 15, LanguageId = 2, Text = "햇빛은 온도를 변화시킬 수 있으며 일조계로 측정합니다." },
        new() { Id = 76, LessonContentId = 15, LanguageId = 3, Text = "La luz solar puede cambiar la temperatura y se mide con un registrador de horas de sol." },
        new() { Id = 77, LessonContentId = 15, LanguageId = 4, Text = "阳光可以改变温度，并可以用日照记录仪进行测量。" },
        new() { Id = 78, LessonContentId = 16, LanguageId = 2, Text = "이러한 모든 요소가 함께 작용하여 날씨를 만듭니다." },
        new() { Id = 79, LessonContentId = 16, LanguageId = 3, Text = "Todos estos elementos trabajan juntos para formar nuestro tiempo." },
        new() { Id = 80, LessonContentId = 16, LanguageId = 4, Text = "所有这些因素共同形成了我们的天气。" },
        new() { Id = 81, LessonContentId = 17, LanguageId = 2, Text = "날씨는 빠르게 변할 수 있습니다." },
        new() { Id = 82, LessonContentId = 17, LanguageId = 3, Text = "El tiempo puede cambiar rápidamente." },
        new() { Id = 83, LessonContentId = 17, LanguageId = 4, Text = "天气可能会迅速变化。" },
        new() { Id = 84, LessonContentId = 18, LanguageId = 2, Text = "하루 계획을 세우기 전에 일기 예보를 확인하는 것이 좋습니다." },
        new() { Id = 85, LessonContentId = 18, LanguageId = 3, Text = "Es bueno consultar el pronóstico del tiempo antes de planificar el día." },
        new() { Id = 86, LessonContentId = 18, LanguageId = 4, Text = "在安排一天的计划之前，最好查看天气预报。" },
        new() { Id = 87, LessonContentId = 19, LanguageId = 2, Text = "순환계는 몸 전체를 통해 혈액이 이동하는 시스템입니다." },
        new() { Id = 88, LessonContentId = 19, LanguageId = 3, Text = "El sistema circulatorio es el movimiento de la sangre por todo el cuerpo." },
        new() { Id = 89, LessonContentId = 19, LanguageId = 4, Text = "循环系统是血液在全身流动的系统。" },
        new() { Id = 90, LessonContentId = 20, LanguageId = 2, Text = "혈액은 우리 몸의 세포에 영양분을 운반합니다." },
        new() { Id = 91, LessonContentId = 20, LanguageId = 3, Text = "La sangre transporta nutrientes a las células de nuestro cuerpo." },
        new() { Id = 92, LessonContentId = 20, LanguageId = 4, Text = "血液将营养物质输送到我们身体的细胞。" },
        new() { Id = 93, LessonContentId = 21, LanguageId = 2, Text = "순환계의 주요 기관은 혈관과 심장입니다." },
        new() { Id = 94, LessonContentId = 21, LanguageId = 3, Text = "Los principales órganos del sistema circulatorio son los vasos sanguíneos y el corazón." },
        new() { Id = 95, LessonContentId = 21, LanguageId = 4, Text = "循环系统的主要器官是血管和心脏。" },
        new() { Id = 96, LessonContentId = 22, LanguageId = 2, Text = "혈관에는 동맥, 정맥, 모세혈관의 세 가지 종류가 있습니다." },
        new() { Id = 97, LessonContentId = 22, LanguageId = 3, Text = "Hay tres tipos de vasos sanguíneos: arterias, venas y capilares." },
        new() { Id = 98, LessonContentId = 22, LanguageId = 4, Text = "血管有三种：动脉、静脉和毛细血管。" },
        new() { Id = 99, LessonContentId = 23, LanguageId = 2, Text = "동맥은 산소가 들어 있는 혈액을 심장에서 몸의 다른 부분으로 운반합니다." },
        new() { Id = 100, LessonContentId = 23, LanguageId = 3, Text = "Las arterias llevan sangre oxigenada desde el corazón al resto del cuerpo." },
        new() { Id = 101, LessonContentId = 23, LanguageId = 4, Text = "动脉将含氧血液从心脏输送到身体的其他部位。" },
        new() { Id = 102, LessonContentId = 24, LanguageId = 2, Text = "정맥은 산소가 부족해진 혈액을 심장으로 다시 운반합니다." },
        new() { Id = 103, LessonContentId = 24, LanguageId = 3, Text = "Las venas llevan la sangre con poco oxígeno de vuelta al corazón." },
        new() { Id = 104, LessonContentId = 24, LanguageId = 4, Text = "静脉将缺氧的血液输送回心脏。" },
        new() { Id = 105, LessonContentId = 25, LanguageId = 2, Text = "모세혈관은 동맥과 정맥을 연결하는 아주 작은 혈관입니다." },
        new() { Id = 106, LessonContentId = 25, LanguageId = 3, Text = "Los capilares son vasos sanguíneos muy pequeños que conectan las arterias con las venas." },
        new() { Id = 107, LessonContentId = 25, LanguageId = 4, Text = "毛细血管是连接动脉和静脉的非常细小的血管。" },
        new() { Id = 108, LessonContentId = 26, LanguageId = 2, Text = "우리 몸의 세포는 살아가기 위해 산소가 필요합니다." },
        new() { Id = 109, LessonContentId = 26, LanguageId = 3, Text = "Las células de nuestro cuerpo necesitan oxígeno para sobrevivir." },
        new() { Id = 110, LessonContentId = 26, LanguageId = 4, Text = "我们身体的细胞需要氧气才能生存。" },
        new() { Id = 111, LessonContentId = 27, LanguageId = 2, Text = "심장은 혈액을 폐로 보내고, 폐에서 혈액에 산소가 들어갑니다." },
        new() { Id = 112, LessonContentId = 27, LanguageId = 3, Text = "El corazón bombea sangre a los pulmones, donde la sangre recibe oxígeno." },
        new() { Id = 113, LessonContentId = 27, LanguageId = 4, Text = "心脏将血液泵入肺部，血液在那里获得氧气。" },
        new() { Id = 114, LessonContentId = 28, LanguageId = 2, Text = "산소가 풍부한 혈액은 동맥을 통해 심장에서 몸으로 이동합니다." },
        new() { Id = 115, LessonContentId = 28, LanguageId = 3, Text = "La sangre rica en oxígeno viaja desde el corazón al cuerpo a través de las arterias." },
        new() { Id = 116, LessonContentId = 28, LanguageId = 4, Text = "富含氧气的血液通过动脉从心脏流向身体。" },
        new() { Id = 117, LessonContentId = 29, LanguageId = 2, Text = "사용된 혈액은 정맥을 통해 심장으로 돌아옵니다." },
        new() { Id = 118, LessonContentId = 29, LanguageId = 3, Text = "La sangre que ha sido utilizada regresa al corazón a través de las venas." },
        new() { Id = 119, LessonContentId = 29, LanguageId = 4, Text = "使用过的血液通过静脉返回心脏。" },
        new() { Id = 120, LessonContentId = 30, LanguageId = 2, Text = "심장은 두 개의 펌프처럼 작동하는 근육입니다." },
        new() { Id = 121, LessonContentId = 30, LanguageId = 3, Text = "El corazón es un músculo que funciona como dos bombas." },
        new() { Id = 122, LessonContentId = 30, LanguageId = 4, Text = "心脏是一块像两个泵一样工作的肌肉。" },
        new() { Id = 123, LessonContentId = 31, LanguageId = 2, Text = "심장의 오른쪽은 혈액을 폐로 보내 산소를 얻도록 합니다." },
        new() { Id = 124, LessonContentId = 31, LanguageId = 3, Text = "El lado derecho bombea sangre a los pulmones para obtener oxígeno." },
        new() { Id = 125, LessonContentId = 31, LanguageId = 4, Text = "心脏的右侧将血液泵入肺部以获得氧气。" },
        new() { Id = 126, LessonContentId = 32, LanguageId = 2, Text = "심장의 왼쪽은 산소가 풍부한 혈액을 몸 전체로 보냅니다." },
        new() { Id = 127, LessonContentId = 32, LanguageId = 3, Text = "El lado izquierdo bombea sangre rica en oxígeno al cuerpo." },
        new() { Id = 128, LessonContentId = 32, LanguageId = 4, Text = "心脏的左侧将富含氧气的血液泵送到全身。" }
    ];
}
