namespace Dookamp.Infrastructure.Seed;

public static class QuizOptionLanguageSeedData
{
    public static IReadOnlyList<QuizOptionLanguageSeed> AdditionalLanguages { get; } =
    [
        new() { Id = 29, QuizOptionId = 1, LanguageId = 2, Text = "공기와 하늘의 상태" },
        new() { Id = 30, QuizOptionId = 1, LanguageId = 3, Text = "Cómo están el aire y el cielo" },
        new() { Id = 31, QuizOptionId = 1, LanguageId = 4, Text = "空气和天空的状态" },
        new() { Id = 32, QuizOptionId = 2, LanguageId = 2, Text = "햇빛의 양" },
        new() { Id = 33, QuizOptionId = 2, LanguageId = 3, Text = "Cuánta luz solar hay" },
        new() { Id = 34, QuizOptionId = 2, LanguageId = 4, Text = "阳光的多少" },
        new() { Id = 35, QuizOptionId = 3, LanguageId = 2, Text = "바람이 얼마나 빠르게 움직이는지" },
        new() { Id = 36, QuizOptionId = 3, LanguageId = 3, Text = "Qué tan rápido se mueve el viento" },
        new() { Id = 37, QuizOptionId = 3, LanguageId = 4, Text = "风移动的速度" },
        new() { Id = 38, QuizOptionId = 4, LanguageId = 2, Text = "참" },
        new() { Id = 39, QuizOptionId = 4, LanguageId = 3, Text = "Verdadero" },
        new() { Id = 40, QuizOptionId = 4, LanguageId = 4, Text = "正确" },
        new() { Id = 41, QuizOptionId = 5, LanguageId = 2, Text = "거짓" },
        new() { Id = 42, QuizOptionId = 5, LanguageId = 3, Text = "Falso" },
        new() { Id = 43, QuizOptionId = 5, LanguageId = 4, Text = "错误" },
        new() { Id = 44, QuizOptionId = 6, LanguageId = 2, Text = "온도계" },
        new() { Id = 45, QuizOptionId = 6, LanguageId = 3, Text = "Termómetro" },
        new() { Id = 46, QuizOptionId = 6, LanguageId = 4, Text = "温度计" },
        new() { Id = 47, QuizOptionId = 7, LanguageId = 2, Text = "습도계" },
        new() { Id = 48, QuizOptionId = 7, LanguageId = 3, Text = "Higrómetro" },
        new() { Id = 49, QuizOptionId = 7, LanguageId = 4, Text = "湿度计" },
        new() { Id = 50, QuizOptionId = 8, LanguageId = 2, Text = "풍속계" },
        new() { Id = 51, QuizOptionId = 8, LanguageId = 3, Text = "Anemómetro" },
        new() { Id = 52, QuizOptionId = 8, LanguageId = 4, Text = "风速计" },
        new() { Id = 53, QuizOptionId = 9, LanguageId = 2, Text = "비" },
        new() { Id = 54, QuizOptionId = 9, LanguageId = 3, Text = "Lluvia" },
        new() { Id = 55, QuizOptionId = 9, LanguageId = 4, Text = "雨" },
        new() { Id = 56, QuizOptionId = 10, LanguageId = 2, Text = "눈" },
        new() { Id = 57, QuizOptionId = 10, LanguageId = 3, Text = "Nieve" },
        new() { Id = 58, QuizOptionId = 10, LanguageId = 4, Text = "雪" },
        new() { Id = 59, QuizOptionId = 11, LanguageId = 2, Text = "진눈깨비" },
        new() { Id = 60, QuizOptionId = 11, LanguageId = 3, Text = "Aguanieve" },
        new() { Id = 61, QuizOptionId = 11, LanguageId = 4, Text = "雨夹雪" },
        new() { Id = 62, QuizOptionId = 12, LanguageId = 2, Text = "우박" },
        new() { Id = 63, QuizOptionId = 12, LanguageId = 3, Text = "Granizo" },
        new() { Id = 64, QuizOptionId = 12, LanguageId = 4, Text = "冰雹" },
        new() { Id = 65, QuizOptionId = 13, LanguageId = 2, Text = "움직이는 공기" },
        new() { Id = 66, QuizOptionId = 13, LanguageId = 3, Text = "Aire en movimiento" },
        new() { Id = 67, QuizOptionId = 13, LanguageId = 4, Text = "流动的空气" },
        new() { Id = 68, QuizOptionId = 14, LanguageId = 2, Text = "수증기" },
        new() { Id = 69, QuizOptionId = 14, LanguageId = 3, Text = "Vapor de agua" },
        new() { Id = 70, QuizOptionId = 14, LanguageId = 4, Text = "水蒸气" },
        new() { Id = 71, QuizOptionId = 15, LanguageId = 2, Text = "구름" },
        new() { Id = 72, QuizOptionId = 15, LanguageId = 3, Text = "Nube" },
        new() { Id = 73, QuizOptionId = 15, LanguageId = 4, Text = "云" },
        new() { Id = 74, QuizOptionId = 16, LanguageId = 2, Text = "참" },
        new() { Id = 75, QuizOptionId = 16, LanguageId = 3, Text = "Verdadero" },
        new() { Id = 76, QuizOptionId = 16, LanguageId = 4, Text = "正确" },
        new() { Id = 77, QuizOptionId = 17, LanguageId = 2, Text = "거짓" },
        new() { Id = 78, QuizOptionId = 17, LanguageId = 3, Text = "Falso" },
        new() { Id = 79, QuizOptionId = 17, LanguageId = 4, Text = "错误" },
        new() { Id = 80, QuizOptionId = 18, LanguageId = 2, Text = "하늘에 있는 구름의 수" },
        new() { Id = 81, QuizOptionId = 18, LanguageId = 3, Text = "Cuántas nubes hay en el cielo" },
        new() { Id = 82, QuizOptionId = 18, LanguageId = 4, Text = "天空中有多少云" },
        new() { Id = 83, QuizOptionId = 19, LanguageId = 2, Text = "내리는 비의 양" },
        new() { Id = 84, QuizOptionId = 19, LanguageId = 3, Text = "Cuánta lluvia cae" },
        new() { Id = 85, QuizOptionId = 19, LanguageId = 4, Text = "降雨量" },
        new() { Id = 86, QuizOptionId = 20, LanguageId = 2, Text = "바람이 얼마나 빠르게 움직이는지" },
        new() { Id = 87, QuizOptionId = 20, LanguageId = 3, Text = "Qué tan rápido se mueve el viento" },
        new() { Id = 88, QuizOptionId = 20, LanguageId = 4, Text = "风移动的速度" },
        new() { Id = 89, QuizOptionId = 21, LanguageId = 2, Text = "공기가 누르는 무게" },
        new() { Id = 90, QuizOptionId = 21, LanguageId = 3, Text = "El peso del aire que presiona hacia abajo" },
        new() { Id = 91, QuizOptionId = 21, LanguageId = 4, Text = "空气向下施加的重量" },
        new() { Id = 92, QuizOptionId = 22, LanguageId = 2, Text = "햇빛의 양" },
        new() { Id = 93, QuizOptionId = 22, LanguageId = 3, Text = "La cantidad de luz solar" },
        new() { Id = 94, QuizOptionId = 22, LanguageId = 4, Text = "阳光的多少" },
        new() { Id = 95, QuizOptionId = 23, LanguageId = 2, Text = "공기 중의 물의 양" },
        new() { Id = 96, QuizOptionId = 23, LanguageId = 3, Text = "La cantidad de agua en el aire" },
        new() { Id = 97, QuizOptionId = 23, LanguageId = 4, Text = "空气中的水量" },
        new() { Id = 98, QuizOptionId = 24, LanguageId = 2, Text = "참" },
        new() { Id = 99, QuizOptionId = 24, LanguageId = 3, Text = "Verdadero" },
        new() { Id = 100, QuizOptionId = 24, LanguageId = 4, Text = "正确" },
        new() { Id = 101, QuizOptionId = 25, LanguageId = 2, Text = "거짓" },
        new() { Id = 102, QuizOptionId = 25, LanguageId = 3, Text = "Falso" },
        new() { Id = 103, QuizOptionId = 25, LanguageId = 4, Text = "错误" },
        new() { Id = 104, QuizOptionId = 26, LanguageId = 2, Text = "일기 예보" },
        new() { Id = 105, QuizOptionId = 26, LanguageId = 3, Text = "El pronóstico del tiempo" },
        new() { Id = 106, QuizOptionId = 26, LanguageId = 4, Text = "天气预报" },
        new() { Id = 107, QuizOptionId = 27, LanguageId = 2, Text = "온도계" },
        new() { Id = 108, QuizOptionId = 27, LanguageId = 3, Text = "Termómetro" },
        new() { Id = 109, QuizOptionId = 27, LanguageId = 4, Text = "温度计" },
        new() { Id = 110, QuizOptionId = 28, LanguageId = 2, Text = "일조계" },
        new() { Id = 111, QuizOptionId = 28, LanguageId = 3, Text = "Registrador de horas de sol" },
        new() { Id = 112, QuizOptionId = 28, LanguageId = 4, Text = "日照记录仪" }
    ];
}
